ci: ensure minimum pip version used is same as tox's pipprevious
fixes the following error

```
ERROR: Cannot install -r requirements-dev.txt (line 86) and pip==21.3.* because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested pip==21.3.*
    pip-tools 6.12.3 depends on pip>=22.2

```